apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: skillsly-notification-handler-backend-config
spec:
  sessionAffinity:
    affinityType: "CLIENT_IP"
  timeoutSec: 300
  connectionDraining:
    drainingTimeoutSec: 600
