# Generated by Django 2.2.12 on 2022-05-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsly_service_ms', '0002_auto_20220421_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_id',
            field=models.CharField(max_length=50, verbose_name='applicant_id'),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='provider_id'),
        ),
        migrations.AlterField(
            model_name='service',
            name='requester_id',
            field=models.CharField(max_length=50, verbose_name='requester_id'),
        ),
    ]
