apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: jonatlop07/skillsly-ag
      context: skillsly-ag
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jonatlop07/skillsly-auth-ms
      context: skillsly-auth-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jonatlop07/skillsly-user-ms
      context: skillsly-user-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jonatlop07/skillsly-story-ms
      context: skillsly-story-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.rs'
            dest: .
    - image: jonatlop07/skillsly-posts-ms
      context: skillsly-posts-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.java'
            dest: .
    - image: jonatlop07/skillsly-comment-ms
      context: skillsly-comment-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: jonatlop07/skillsly-service-ms
      context: skillsly-service-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './**/*.py'
            dest: .
    - image: jonatlop07/skillsly-storage-ms
      context: skillsly-storage-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: './**/*.py'
            dest: .
    - image: jonatlop07/skillsly-notification-ms
      context: skillsly-notification-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jonatlop07/skillsly-notification-handler-ms
      context: skillsly-notification-handler-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
