apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skillsly-backend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: skillsly-api
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - skillsly.app
        - ldap.skillsly.app
        - notification.skillsly.app
        - soap.skillsly.app
        - api.skillsly.app
      secretName: skillsly-certificate

  rules:
    - host: "skillsly.app"
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: skillsly-wa-srv
                port:
                  name: wa
    - host: "notification.skillsly.app"
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: skillsly-notification-handler-ms-srv
                port:
                  name: notification
    - host: "ldap.skillsly.app"
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: skillsly-ldap-srv
                port:
                  name: ldap
    - host: "api.skillsly.app"
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: skillsly-ag-srv
                port:
                  name: api-gateway
    - host: "soap.skillsly.app"
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: skillsly-interface-srv
                port:
                  name: interface