# Generated by Django 2.2.12 on 2022-04-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_id', models.IntegerField(verbose_name='requester_id')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('contact_info', models.CharField(max_length=200, verbose_name='contact_info')),
                ('category', models.CharField(max_length=60, verbose_name='category')),
                ('phase', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('evaluation', 'Evaluation'), ('execution', 'Execution'), ('finished', 'Finished')], default='open', max_length=10, verbose_name='phase')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('provider_id', models.IntegerField(verbose_name='provider_id')),
                ('canceled', models.BooleanField(default=False, verbose_name='canceled')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField(verbose_name='applicant_id')),
                ('message', models.CharField(blank=True, max_length=300, null=True, verbose_name='message')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsly_service_ms.Service')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
