version: "3.7"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  redis-commander:
    image: "rediscommander/redis-commander:latest"
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis
  skillsly_notification_mq:
    image: rabbitmq:3.10-rc-management-alpine
    container_name: skillsly_notification_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    env_file:
      - ./env/rabbitmq.env
  skillsly_notification_handler_ms:
    build: .
    container_name: skillsly_notification_handler_ms
    depends_on:
      - redis
      - skillsly_notification_mq
    environment:
      API_HOST: localhost
      API_PORT: 3000
      API_ENABLE_LOG: true
      MQ_PROTOCOL: amqp
      MQ_HOST: skillsly_notification_mq
      MQ_PORT: 5672
      MQ_USERNAME: skillsly_notification
      MQ_PASSWORD: notification
      MQ_QUEUE: notifications_queue
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TTL_CACHE: 600
    ports:
      - "8012:3000"
      - "9233:9229"
  skillsly_notification_db:
    container_name: skillsly_notification_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: skillsly
      POSTGRES_PASSWORD: notification
      POSTGRES_DB: skillsly_notification_db
    volumes:
      - ../skillsly_notification_ms/skillsly_notification_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "35002:5432"
  skillsly_notification_ms:
    build: ../skillsly_notification_ms
    container_name: skillsly_notification_ms
    depends_on:
      - skillsly_notification_db
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 3001
      API_ENABLE_LOG: true
      DATABASE_URL: postgres://skillsly:notification@skillsly_notification_db:5432/skillsly_notification_db
    ports:
      - "8011:3001"
      - "9232:9229"


