version: "3.7"

services:
  skillsly_notification_mq:
    image: rabbitmq:3-management-alpine
    container_name: skillsly_notification_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    env_file:
      - ./env/rabbitmq
  skillsly_notification_handler_ms:
    build: .
    container_name: skillsly_notification_handler_ms
    depends_on:
      - skillsly_notification_handler_mq
    environment:
      API_HOST: localhost
      API_PORT: 3000
      API_ENABLE_LOG: true
      MQ_PROTOCOL: amqp
      MQ_HOST: skillsly_notification_mq
      MQ_PORT: 5672
      MQ_USERNAME: skillsly_notification
      MQ_PASSWORD: notification
      MQ_QUEUE: notifications_queue
    ports:
      - "8011:3000"
      - "9232:9229"


