apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillsly-posts-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillsly-posts-db
  template:
    metadata:
      labels:
        app: skillsly-posts-db
    spec:
      containers:
        - name: skillsly-posts-db
          image: mongo:latest
          env:
            - name: MONGO_DATA_PATH
              value: /data/db
            - name: MONGO_LOG_PATH
              value: /dev/null
            - name: MONGODB_DATABASE
              value: skillsly_posts_db
---
apiVersion: v1
kind: Service
metadata:
  name: skillsly-posts-db-srv
spec:
  selector:
    app: skillsly-posts-db
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
