version: "3.6"

services:
  skillsly_auth_db:
    container_name: skillsly_auth_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: skillsly
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: skillsly_auth_db
    volumes:
      - ./skillsly_auth_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "35000:5432"
  skillsly_auth_ms:
    build: .
    container_name: skillsly_auth_ms
    depends_on:
      - skillsly_auth_db
    environment:
      DATABASE_URL: postgres://skillsly:auth@skillsly_auth_db:5432/skillsly_auth_db
      API_HOST: localhost
      API_PORT:  3000
      API_ENABLE_LOG: true
      AUTH_DB_HOST: localhost
      AUTH_DB_PORT: 5432
      AUTH_DB_USERNAME: skillsly
      AUTH_DB_PASSWORD: auth
      AUTH_DB_NAME: skillsly_auth_db
      AUTH_DB_ENABLE_LOG: true
      JWT_SECRET: Rx334Juo_a2
      JWT_EXPIRATION_TIME: 60
      THROTTLE_TTL: 60
      THROTTLE_LIMIT: 200
      TWO_FACTOR_AUTHENTICATION_APP_NAME: skillsly
      CAPTCHA_SITE_KEY: 6Le-PfMdAAAAAPbJ8IEDDRkETuRyWBbDViisYyIe
      MAILER_HOST: smtp.gmail.com
      MAILER_PORT: 465
      MAILER_IGNORE_TLS: false
      MAILER_SECURE: false
      USER_MAILER: SkillslyTeam@gmail.com
      PASS_MAILER: kdeddnrigplubqdj
    ports:
      - "8000:3000"
      - "9239:9229"
