version: "3.6"

services:
  skillsly_ldap:
    image: osixia/openldap:1.1.8
    container_name: skillsly_ldap
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Skillsly"
      LDAP_DOMAIN: "skillsly.dev"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "skillsly.dev"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: skillsly_php_ldap_client
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "skillsly_ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    links:
      - skillsly_ldap
  skillsly_auth_db:
    container_name: skillsly_auth_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: skillsly
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: skillsly_auth_db
    volumes:
      - ./skillsly_auth_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "35000:5432"
  skillsly_auth_ms:
    build: .
    container_name: skillsly_auth_ms
    depends_on:
      - skillsly_auth_db
    environment:
      DATABASE_URL: postgres://skillsly:auth@skillsly_auth_db:5432/skillsly_auth_db
      API_HOST: '0.0.0.0'
      API_PORT: '3000'
      API_ENABLE_LOG: 'true'
      AUTH_DB_ENABLE_LOG: 'true'
      JWT_SECRET: 'Rx334Juo_a2'
      JWT_EXPIRATION_TIME: '60'
      THROTTLE_TTL: '60'
      THROTTLE_LIMIT: '200'
      TWO_FACTOR_AUTHENTICATION_APP_NAME: 'skillsly'
      CAPTCHA_SITE_KEY: '6Le-PfMdAAAAAPbJ8IEDDRkETuRyWBbDViisYyIe'
      MAILER_HOST: 'smtp.gmail.com'
      MAILER_PORT: '465'
      MAILER_IGNORE_TLS: 'false'
      MAILER_SECURE: 'false'
      USER_MAILER: 'SkillslyTeam@gmail.com'
      PASS_MAILER: 'kdeddnrigplubqdj'
    ports:
      - "8001:3000"
      - "9229:9229"
