version: "3.6"

services:
  skillsly_auth_db:
    container_name: skillsly_auth_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: skillsly
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: skillsly_auth_db
    volumes:
      - ./skillsly_auth_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "35000:5432"
  skillsly_auth_ms:
    build: .
    container_name: skillsly_auth_ms
    depends_on:
      - skillsly_auth_db
    environment:
      DATABASE_URL: postgres://skillsly:auth@skillsly_auth_db:5432/skillsly_auth_db
    ports:
      - "8000:3000"
      - "9229:9229"
