kind: PersistentVolume
apiVersion: v1
metadata:
  name: skillsly-notification-db-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/data/notification-db
