version: "3.7"

services:
  skillsly_story_db:
    container_name: skillsly_story_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: skillsly
      POSTGRES_PASSWORD: story
      POSTGRES_DB: skillsly_story_db
    volumes:
      - ./skillsly_story_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "35003:5432"
  skillsly_story_ms:
    build: .
    container_name: skillsly_story_ms
    depends_on:
      - skillsly_story_db
    environment:
      DATABASE_URL: postgres://skillsly:story@skillsly_story_db:5432/skillsly_story_db
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
    ports:
      - "8003:8000"
