apiVersion: v1
kind: Service
metadata:
  name: skillsly-interface-srv
spec:
  ports:
    - name: interface
      port: 8080
      protocol: TCP
      targetPort: 8080
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: skillsly-interface-srv
subsets:
  - addresses:
      - ip: 192.168.0.18
    ports:
      - name: interface
        port: 8080
        protocol: TCP
