from .ServiceRegistView import *
from .ServiceListView import *
from .ApplicationRegistView import *
from .ServiceApplicationsListView import *
from .ServiceRUDView import *
from .ServicePhaseUpdateView import *
from .ServiceStatusUpdateView import *
from .ApplicationRUDView import *
from .ServiceProviderUpdateView import *