apiVersion: v1
kind: Secret
metadata:
  name: skillsly-notification-mq-secret
type: Opaque
data:
  RABBITMQ_ERLANG_COOKIE: WkZJWEFLVEdHRk9JSFlFWEVEU1oK
  user: c2tpbGxzbHlfbm90aWZpY2F0aW9uCg==
  pass: bm90aWZpY2F0aW9uCg==
