apiVersion: v1
kind: ServiceAccount
metadata:
  name: skillsly-notification-rabbitmq-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: skillsly-notification-rabbitmq-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: skillsly-notification-rabbitmq-rb
subjects:
  - kind: ServiceAccount
    name: skillsly-notification-rabbitmq-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skillsly-notification-rabbitmq-role
