apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skillsly-backend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: skillsly-api
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - host: "34.122.26.102.nip.io"
      http:
        paths:
          - pathType: Prefix
            path: /graphql
            backend:
              service:
                name: skillsly-ag-srv
                port:
                  name: api-gateway
  tls:
    - hosts:
      - 34.122.26.102.nip.io
      secretName : skillsly-certificate


#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: skillsly-frontend-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
#    nginx.ingress.kubernetes.io/enable-cors: 'true'
#    nginx.ingress.kubernetes.io/use-regex: 'true'
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: "skillsly.dev"
#      http:
#        paths:
#          - pathType: Prefix
#            path: /?(.*)
#            backend:
#              service:
#                name: skillsly-wa-srv
#                port:
#                  name: wa
