version: "3.7"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  redis-commander:
    image: "rediscommander/redis-commander:latest"
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
  skillsly_ag:
    build: .
    container_name: skillsly_ag
    environment:
      API_HOST: '0.0.0.0'
      API_PORT: '3000'
      API_ENABLE_LOG: 'true'
      REDIS_HOST: redis
    depends_on:
      - redis
    ports:
      - "8010:3000"
      - "9232:9229"
