apiVersion: v1
kind: ConfigMap
metadata:
  name: skillsly-notification-ms-env-config
data:
  API_HOST: '0.0.0.0'
  API_PORT: '3000'
  API_ENABLE_LOG: 'true'
  DATABASE_URL: 'postgres://postgres:notification@34.135.100.171:5432/postgres'
  NOTIFICATION_DB_ENABLE_LOG: 'true'
  MQ_PROTOCOL: 'amqp'
  MQ_HOST: 'skillsly-notification-mq-0.skillsly-notification-mq-srv.default.svc.cluster.local'
  MQ_PORT: '5672'
  MQ_USERNAME: 'skillsly_notification'
  MQ_PASSWORD: 'notification'
  MQ_QUEUE: 'notifications_queue'
