apiVersion: v1
kind: Service
metadata:
  name: skillsly-notification-handler-ms-srv
spec:
  ports:
    - name: notification
      port: 3000
      protocol: TCP
      targetPort: 3000
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: skillsly-notification-handler-ms-srv
subsets:
  - addresses:
      - ip: 192.168.15.219
    ports:
      - name: notification
        port: 3000
        protocol: TCP
