apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillsly_user_ms_depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillsly_user_ms
  template:
    metadata:
      labels:
        app: skillsly_user_ms
    spec:
      containers:
        - name: skillsly_user_ms
          image: skillsly_user_ms
          env:
            - name: DATABASE_URL
              value: 'postgres://skillsly:user@skillsly_user_db_srv:5432/skillsly_user_db'
---
apiVersion: v1
kind: Service
metadata:
  name: skillsly_user_ms_srv
spec:
  selector:
    app: skillsly_user_ms
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 8002
