apiVersion: v1
kind: ConfigMap
metadata:
  name: skillsly-user-ms-env-config
data:
  API_HOST: '0.0.0.0'
  API_PORT: '3000'
  API_ENABLE_LOG: 'true'
  DATABASE_URL: 'postgres://skillsly:user@skillsly-user-db-srv:5432/skillsly_user_db'
  USER_DB_ENABLE_LOG: 'true'
  THROTTLE_TTL: '60'
  THROTTLE_LIMIT: '200'
