apiVersion: v1
kind: Service
metadata:
  name: skillsly-wa-srv
spec:
  ports:
    - name: wa
      port: 4200
      protocol: TCP
      targetPort: 4200
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: skillsly-wa-srv
subsets:
  - addresses:
      - ip: 192.168.15.220
    ports:
      - name: wa
        port: 4200
        protocol: TCP
