apiVersion: v1
kind: Service
metadata:
  name: skillsly-ag-srv
spec:
  ports:
    - name: api-gateway
      port: 3000
      protocol: TCP
      targetPort: 3000
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: skillsly-ag-srv
subsets:
  - addresses:
      - ip: 192.168.0.17
    ports:
      - name: api-gateway
        port: 3000
        protocol: TCP
