port: 8002

mongo:
  uri: "mongodb+srv://angegonzalez:angegonzalez@skillslychatdb.ljndb.mongodb.net/skillsly_chat_db?retryWrites=true&w=majority"
  name: "skillsly_chat_db"
  conversations_collection: "conversations"
  messages_collection: "messages"
