port: 8002

mongo:
  uri: "mongodb+srv://admin:1234@skillslychatdb.ljndb.mongodb.net/?retryWrites=true&w=majority"
  name: "skillsly_chat_db"
  conversations_collection: "conversations"
  messages_collection: "messages"
