version: "3.6"

services:
  skillsly_user_db:
    container_name: skillsly_user_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: skillsly
      POSTGRES_PASSWORD: user
      POSTGRES_DB: skillsly_user_db
    volumes:
      - ./skillsly_user_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "35001:5432"
  skillsly_user_ms:
    build: .
    container_name: skillsly_user_ms
    depends_on:
      - skillsly_user_db
    environment:
      DATABASE_URL: postgres://skillsly:user@skillsly_user_db:5432/skillsly_user_db
    ports:
      - "8001:3000"
      - "9229:9229"
