version: "3.7"

services:
  skillsly_user_db:
    container_name: skillsly_user_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: skillsly
      POSTGRES_PASSWORD: user
      POSTGRES_DB: skillsly_user_db
    volumes:
      - ./skillsly_user_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "35001:5432"
  skillsly_user_ms:
    build: .
    container_name: skillsly_user_ms
    depends_on:
      - skillsly_user_db
    environment:
      API_HOST: '0.0.0.0'
      API_PORT: '3000'
      API_ENABLE_LOG: 'true'
      DATABASE_URL: 'postgres://skillsly:user@skillsly_user_db:5432/skillsly_user_db'
      USER_DB_ENABLE_LOG: 'true'
      THROTTLE_TTL: '60'
      THROTTLE_LIMIT: '200'
    ports:
      - "8002:3000"
      - "9230:9229"
